[build]
rustc-wrapper = "sccache"

[target.armv7-unknown-linux-musleabihf]
linker = "/opt/muslcc/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc"

# [target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "linker=clang", "-C", "link-args=-fuse-ld=lld"]

# [registries.crates-io]
# protocol = "sparse"
