return {
  Text        = '韛',
  Function    = '',
  Method      = ' ',
  Constructor = ' ',
  Variable    = '凜',
  Class       = '﬿ ',
  Interface   = '擄',
  Module      = '璉',
  Property    = 'ﯟ ',
  Unit        = ' ',
  Value       = '藍',
  Enum        = ' ',
  Keyword     = ' ',
  Snippet     = ' ',
  Color       = ' ',
  File        = ' ',
  Folder      = ' ',
  EnumMember  = ' ',
  Constant    = ' ',
  Struct      = ' ',
  Field       = ' ',
}
