return {
  kind_labels = {
    Text = "󰗊",
    Function = "󰊕",
    Method = " ",
    Constructor = " ",
    Variable = "󰑕",
    Class = "󰠱 ",
    Interface = "󰐱",
    Module = "󰒕",
    Property = "󰛡 ",
    Unit = " ",
    Value = "󰐤",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = "󰐀 ",
    Struct = " ",
    Field = " ",
  },
  signs = {
    error = " ",
    warn = " ",
    info = " ",
    hint = "󰌵 ",
    -- error = "󰅚 ",
    -- warn = "󰀪 ",
    -- info = " ",
    -- hint = "󰌶 ",
  },
  diff = {
    added = " ",
    modified = " ",
    removed = " ",
  },
}
