return {
  kind_labels = {
    Text = "韛",
    Function = "",
    Method = " ",
    Constructor = " ",
    Variable = "凜",
    Class = "ﴯ ",
    Interface = "擄",
    Module = "璉",
    Property = "ﯟ ",
    Unit = " ",
    Value = "藍",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Field = " ",
  },
  signs = {
    -- error       = ' ',
    -- warn        = ' ',
    -- info        = ' ',
    -- hint        = ' '
    error = " ",
    warn = " ",
    info = " ",
    hint = " ",
  },
}
